spring:
  application:
    name: ${APP_NAME:kafka-producer-service}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic: ${KAFKA_TOPIC}
scheduler:
  fixed-rate: ${SCHEDULE_TIME:5000}
management:
  health:
    show-details: always
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
    endpoint:
      prometheus:
        enabled: true
      health:
        enabled: true
server:
  port: ${SERVER_PORT}
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
    org:
      hibernate:
        type: ${LOGGING_LEVEL_HIBERNATE_TYPE}